# ░░░░░░░░░░░░░░░   CorePlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/coreplus.86532/
#  Wiki: https://github.com/momoservertw/CorePlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 1
Check-Updates: true
Debugging: false

General:
  # Translating the placeholders of vanilla Items, Entities, Enchantment name to player client language.
  # Need to setup. More information: https://github.com/momoservertw/CorePlus/wiki/Vanilla-Translation
  Vanilla-Translation:
    Enable: true
    Force:
      Enable: false
      Local: ""
  # Using a item as menu to trigger some features.
  Menu:
    # To custom item node from plugin ItemJoin.
    ItemJoin: ""
    Item:
      Type: "PLAYER_HEAD"
      # Setting this option to "" to use vanilla item as menu.
      Name: "&e&lMy &6&lMenu"
      Skull-Textures: ""
  Features:
    # Changed these options need to restart the server.
    Hook:
      Vault: true
      PlayerPoints: true
      GemsEconomy: true
      PlaceHolderAPI: true
      DiscordSRV: true
      LuckPerms: true
      MysqlPlayerDataBridge: true
      CMI: true
      Residence: true
      MythicMobs: true
      ItemJoin: true
      AuthMe: true

# To create a custom configurations.
# More information: https://github.com/momoservertw/CorePlus/wiki/Config-Builder
Config-Builder:
  Settings:
    Material:
      # Creating a temporary block data to build the Material list. Only changed if you get errors.
      Temporary-Block-Data:
        World: world
        Radius: 30
  # To create groups.yml configuration in the path from log.yml "GroupsConfig".
  # Command: /crp configbuilder groups
  Groups:
    Entities:
      All:
        # Can be a Group of types or entity type.
        List:
          - all
        Ignore-List: []
      LivingEntity:
        List:
          - LivingEntity
      Items:
        List:
          - Item
      Monsters:
        List:
          - Monster
          - Flying
      Normal:
        List:
          - Monster
          - Flying
        Ignore-List:
          - Boss
      Animals:
        List:
          - Animals
      Breedable:
        List:
          - Breedable
      Pets:
        List:
          - Tameable
          - Fox
          - Golem
        Ignore-List:
          - Shulker
      ChestedHorse:
        List:
          - ChestedHorse
      Useless:
        List:
          - Bat
          - Fish
          - BAT
    Materials:
      All:
        List:
          - all
        Ignore-List: []
      Container:
        List:
          - Chest
          - Furnace
          - Hopper
          - BrewingStand
          - Dispenser
      Usable:
        List:
          - Chest
          - Furnace
          - Hopper
          - BrewingStand
          - Dispenser
          - ANVIL

          - Powerable
          - Jukebox
          - EnderChest
          - Bed
          - CRAFTING_TABLE
          - SHULKER_BOX{endsWith;}
      Machines:
        List:
          - Powerable
          - PistonHead
          - Piston
          - Hopper
          - Comparator
          - DaylightDetector
  # To create a custom configuration in the path of log.yml "CustomConfig".
  # Command: /crp configbuilder custom <Type> <Group>
  Custom:
    OfflinePlayer-UUID:
      Type: OfflinePlayer-UUID
      Format:
        Title: "%title%:"
        Row-Line: true
        Value: "  - %value%"
        #Value: "%value%:"
        #Split: ", "
      # Can be UUID or Player name.
      Ignore-List: []
    OfflinePlayer-Name:
      Type: OfflinePlayer-Name
      Format:
        Title: "%title%:"
        Row-Line: true
        Value: "  - %value%"
        #Split: ", "
      Ignore-List: []
    Example-Entity-Group:
      Type: entity
      Format:
        Title: "%title%:"
        Row-Line: true
        Value: "  - %value%"
        #Split: ", "
      List:
        - Boss
      Ignore-List: []
    Example-Material-Group:
      Type: material
      Format:
        Title: "%title%:"
        Row-Line: true
        Value: "  - %value%"
        #Split: ", "
      List:
        - Chest
      Ignore-List: []

Message:
  prefix: "&7[&dCorePlus&7]&r "
  unknownCommand: "&fUnknown command."
  noPermission: "&cYou do not have permission to use that command!"
  configReload: "&aConfiguration(s) Reloaded!"
  targetNotFound: "&cThe player &c%targetplayer% &ccould not be found!"
  cooldown: "&fPlease try it again later."
  featureDisabled: "&cThis feature is disabled."
  dependNotFound: "&cThis feature needs plugin %plugin%."
  groupNotFound: "&cCan not find: %group%"
  onlyPlayer: "&cThis command can only executing from player."
  noFlagPerm: "&cYou dont have &6%flag% &cpermission<s> here."
  notEnoughMoney: "&cYou need %pricetype%: %price% - Balance: %balance%"
  notEnoughMoneyTarget: "&c%targetplayer% need %pricetype%: %price% - Balance: %balance%"
  inventoryFull: "&cYou don't have enough inventory space."
  inventoryFullTarget: '&c%targetplayer% dont have enough inventory space.'
  noShopItem: "&cYou can not buy this block."
  buySuccess: "&aSuccess buy &e%item% x%amount% &afor %price% %pricetype% &8- &a%pricetype%: %balance%"
  buyTargetSuccess: "&aSuccess buy &e%item% x%amount% &afor %price% %pricetype% for %targetplayer% &8- &a%pricetype%: %balance%"
  runcmdOther: "&eExecuted command for %targetplayer%: %command%"
  runcmdCustomOther: "&eExecuted custom command for %targetplayer%: %group%"
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩ &d&lCorePlus &8▩▩▩▩▩▩▩▩▩▩"
    help: "&f/coreplus help &8- &7This help menu."
    reload: "&f/coreplus reload &8- &7Reloads config file."
    version: "&f/coreplus version &8- &7Checks the plugin version and updates."
    test: "&f/coreplus test <location/blocks/> <group> &8- &7Checks if the condition is match."
    testPlaceholder: "&f/coreplus test <placeholder> &8- &7Toggles the placeholder debug mode."
    configbuilderCustom: "&f/coreplus configbuilder custom <group> &8- &7Creates a configuration for custom group."
    configbuilderGroup: "&f/coreplus configbuilder group &8- &7Creates a configuration for group.yml."
    cmdcustom: "&f/coreplus cmdcustom [player] <group> &8- &7Executes custom group command for a player."
    cmd: "&f/coreplus cmd <command> &8- &7Executes custom command."
    cmdplayer: "&f/coreplus cmdplayer <player> <command> &8- &7Executes custom command for a player."
    cmdonline: "&f/coreplus cmdonline <player> <expiration> <command> &8- &7Executes the custom command after the player joined the server."
  Translation:
    console: "Console"
    noTargets: "No Target"
    noData: "No Data"
    money: "money"
    points: "points"
    res_points: "points"
    Blocks: "blocks"
    resCreate: "create residence"
    resChangeSize: "change residence size"
    fishing: "fishing"
    usingItem: "using items"
    interactBlock: "interact blocks"
    interactEntity: "interact entities"
    damamgeEntity: "damage entities"
    dropItem: "drop items"
    pickupItem: "pickup items"
    colorA: "green"
    colorB: "aqua"
    colorC: "red"
    colorD: "light_purple"
    colorE: "yellow"
    colorF: "white"
    color0: "black"
    color1: "dark_blue"
    color2: "dark_green"
    color3: "dark_aqua"
    color4: "dark_red"
    color5: "dark_purple"
    color6: "gold"
    color7: "gray"
    color8: "dark_gray"
    color9: "blue"