name: CorePlus
main: tw.momocraft.coreplus.CorePlus
author: Momocraft
api-version: 1.13
version: 1.0.0
description: The API contains all utils for my plugins.
depend: [Vault]
softdepend: [PlayerPoints, GemsEconomy, PlaceHolderAPI, LuckPerms, MysqlPlayerDataBridge, CMI, Residence, ItemJoin, MythicMobs, PvPManager, MultiverseCore, SurvivalMechanics, Vehicles]

commands:
  coreplus:
    description: Displays main command menu.
    permission: coreplus.admin
    aliases: [crp]
    usage: |
      /coreplus

permissions:
  coreplus.*:
    description: Allows use of all commands and features.
    default: op
    children:
      coreplus.use: true
      CorePlus.command.*: true
      CorePlus.bypass.*: true
  CorePlus.use:
    description: Allows use of basic commands.
    default: true
  CorePlus.command.*:
    description: Allows use all commands.
    default: op
    children:
      CorePlus.command.reload: true
      CorePlus.command.version: true
      CorePlus.command.test: true
      CorePlus.command.configbuilder: true
      CorePlus.command.cmdgroup: true
      CorePlus.command.cmd: true
      CorePlus.command.cmdplayer: true
      CorePlus.command.cmdonline: true
  CorePlus.command.reload:
    description: Allows use of /coreplus command reload.
    default: op
  CorePlus.command.version:
    description: Allows use of command /coreplus version.
    default: op
  CorePlus.command.test:
    description: Allows use of command /coreplus test.
    default: op
  CorePlus.command.configbuilder:
    description: Allows use of command /coreplus configbuilder.
  CorePlus.command.cmdgroup:
    description: Allows use of command /coreplus cmdgroup
    default: op
  CorePlus.command.cmd:
    description: Allows use of command /coreplus cmd
    default: op
  CorePlus.command.cmdplayer:
    description: Allows use of command /coreplus cmdplayer.
    default: op
  CorePlus.command.cmdonline:
    description: Allows use of command /coreplus cmdonline.
    default: op