# ░░░░░░░░░░░░░░░   CorePlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/coreplus.86532/
#  Wiki: https://github.com/momoservertw/CorePlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 1
Check-Updates: true
Debugging: false

General:
  # Saving data for some features.
  MySQL:
    username: root
    password: ''
    hostname: localhost
    port: 3306
  # Translating the placeholders of vanilla Item, Entity, Enchantment name to player client language.
  # Need to setup. More information: https://github.com/momoservertw/CorePlus/wiki/Language
  Language:
    Enable: true
    Local:
      Enable: false
      Tag: ""
  # Using a item as menu to trigger some features.
  Menu:
    # To custom item node from plugin ItemJoin.
    ItemJoin: ""
    Item:
      Type: "PLAYER_HEAD"
      # Setting this option to "" to use vanilla item as menu.
      Name: "&e&lMy &6&lMenu"
      Skull-Textures: ""
  Features:
    # Changed these options need to restart the server.
    Hook:
      Vault: true
      PlayerPoints: true
      GemsEconomy: true
      PlaceHolderAPI: true
      DiscordSRV: true
      LuckPerms: true
      MysqlPlayerDataBridge: true
      CMI: true
      Residence: true
      MythicMobs: true
      ItemJoin: true
      AuthMe: true

Message:
  prefix: "&7[&dCorePlus&7]&r "
  unknownCommand: "&f無效的指令"
  noPermission: "&f無效的指令"
  configReload: "&a重新讀取插件資料！"
  targetNotFound: "&c找不到玩家 %targetplayer%"
  cooldown: "&f請稍後再次使用..."
  featureDisabled: "&c沒有啟用此功能"
  dependNotFound: "&c需要插件 %plugin%."
  groupNotFound: "&c找不到: %group%"
  onlyPlayer: "&c只有玩家才可以執行這個指令"
  noFlagPerm: "&c沒有 &6%flag% &c權限"
  notEnoughMoney: "&c沒有足夠的 %pricetype%， 需要 %pricetype%: %price%"
  notEnoughMoneyTarget: "&c%targetplayer% 沒有足夠的 %pricetype%， 需要 %pricetype%: %price%."
  inventoryFull: "&c背包空間不足"
  inventoryFullTarget: '&c%targetplayer% 背包空間不足'
  noShopItem: "&c你無法購買此方塊"
  buySuccess: "&a成功購買 &e%item% &7x%amount% &a價格： %price% %pricetype% &8- &a%pricetype%: %balance%"
  buyTargetSuccess: "&a已讓 %targetplayer% 成功購買 &e%item% x%amount% &a價格 %price% %pricetype% &8- &a%pricetype%: %balance%"
  runcmdOther: "&e以為 %targetplayer% 執行指令: %command%"
  runcmdCustomOther: "&e以為 %targetplayer% 執行自訂指令: %group%"
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩ &d&lCorePlus &8▩▩▩▩▩▩▩▩▩▩"
    help: "&a/coreplus help &8- &7This help menu."
    reload: "&a/coreplus reload &8- &7Reloads config file."
    version: "&f/coreplus version &8- &7Checks the plugin version and updates."
    test: "&f/coreplus test <location/blocks> <group> &8- &7Check if the condition is match."
    runcmd: "&f/coreplus runcmd <command> &8- &7Executing input custom command."
    runcmdOther: "&f/coreplus runcmd <player> <command> &8- &7Executing input custom command for other player."
    runcmdCustom: "&f/coreplus runcmdcustom <group> &8- &7Executing custom command from configuration."
    runcmdCustomOther: "&f/coreplus runcmdcustom <player> <group> &8- &7Executing custom command from configuration for other player."
  Translation:
    money: "遊戲幣"
    points: "代幣"
    res_points: "格數"
    Blocks: "格數"
    resCreate: "新增領地"
    resChangeSize: "更改領地大小"
    noTargets: "無"
    fishing: "釣魚"
    usingItem: "使用物品"
    interactBlock: "接觸方塊"
    interactEntity: "接觸實體"
    damamgeEntity: "傷害生物"
    dropItem: "丟棄物品"
    pickupItem: "撿起物品"