# ░░░░░░░░░░░░░░░   CorePlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/coreplus.86532/
#  Wiki: https://github.com/momoservertw/CorePlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 1
Check-Updates: true
Debugging: false

General:
  MySQL:
    Enable: true
    hostname: localhost
    port: 3306
    username: "root"
    password: ""
  # Translating the placeholders of vanilla Items, Entities, Enchantment name to player client language.
  # Need to setup. More information: https://github.com/momoservertw/CorePlus/wiki/Vanilla-Translation
  Local:
    Enable: true
    Force:
      Enable: false
      Language: ""
  # Using a item as menu to trigger some features.
  Menu:
    # To custom item node from plugin ItemJoin.
    ItemJoin: ""
    Item:
      Type: "PLAYER_HEAD"
      # Setting this option to "" to use vanilla item as menu.
      Name: "&e&lMy &6&lMenu"
      Skull-Textures: ""
  Features:
    # Changed these options need to restart the server.
    Hook:
      Vault: true
      PlayerPoints: true
      GemsEconomy: true
      PlaceHolderAPI: true
      DiscordSRV: true
      LuckPerms: true
      MysqlPlayerDataBridge: true
      CMI: true
      Residence: true
      MythicMobs: true
      ItemJoin: true
      AuthMe: true
      NameTagEdit: true

# To create a custom configurations.
# More information: https://github.com/momoservertw/CorePlus/wiki/Config-Builder
Config-Builder:
  Settings:
    Material:
      # Creating a temporary block data to build the Material list. Only changed if you get errors.
      Temporary-Block-Data:
        World: world
        Radius: 30
  # To create groups.yml configuration in the path from log.yml "GroupsConfig".
  # Command: /crp configbuilder groups
  Groups:
    Entities:
      All:
        # Can be a Group of types or entity type.
        List:
          - all
        Ignore-List: []
      LivingEntity:
        List:
          - LivingEntity
      Items:
        List:
          - Item
      Monsters:
        List:
          - Monster
          - Flying
      NormalMobs:
        List:
          - Monster
          - Flying
        Ignore-List:
          - Boss
      Animals:
        List:
          - Animals
      Breedable:
        List:
          - Breedable
      Pets:
        List:
          - Tameable
          - Fox
          - Golem
        Ignore-List:
          - Shulker
      ChestedHorse:
        List:
          - ChestedHorse
      Useless:
        List:
          - Bat
          - Fish
          - BAT
    Materials:
      All:
        List:
          - all
        Ignore-List: []
      Container:
        List:
          - Chest
          - Furnace
          - Hopper
          - BrewingStand
          - Dispenser
      Usable:
        List:
          - Chest
          - Furnace
          - Hopper
          - BrewingStand
          - Dispenser
          - ANVIL

          - Powerable
          - Jukebox
          - EnderChest
          - Bed
          - CRAFTING_TABLE
          - SHULKER_BOX{endsWith;}
      Machines:
        List:
          - Powerable
          - PistonHead
          - Piston
          - Hopper
          - Comparator
          - DaylightDetector
      NormalBlocks:
        List:
          - STONE
          - WATER
          - ANDESITE
          - DIORITE
          - GRANITE
          - DIRT
          - COAL_ORE
          - GRASS_BLOCK
          - IRON_ORE
          - LAVA
          - SAND
          - KELP_PLANT
          - OAK_LEAVES
          - SANDSTONE
          - RED_SAND
          - RED_SANDSTONE
          - REDSTONE_ORE
          - SNOW
          - BIRCH_LEAVES
          - TALL_SEAGRASS
          - SPRUCE_LEAVES
          - GOLD_ORE
          - SEAGRASS
          - DARK_OAK_LEAVES
          - GRASS
          - KELP
          - ICE
          - LAPIS_ORE
          - Packed Ice
          #- Oak Planks
          - BUBBLE_COLUMN
          - DIAMOND_ORE
          - OBSIDIAN
          - OAK_LOG
          - DARK_OAK_LOG
          #- Oak Fence
          - BIRCH_LOG
          - INFESTED_STONE
          - VINE
          - SPRUCE_LOG
          - CLAY
          - SNOW_BLOCK
          - RAIL
          - COBBLESTONE
          - COBWEB
          - ACACIA_LEAVES
          - TALL_GRASS
          - STONE_BRICK
          - MOSSY_COBBLESTONE
          - RED_MUSHROOM_BLOCK
          - POPPY
          - MOSSY_STONE_BRICKS
          - LARGE_FERN
          - JUNGLE_LEAVES
          - GRASS_PATH
          - DANDELION
          - EMERALD_ORE
          - CRACKED_STONE_BRICKS
          - LILY_PAD
          - FERN
          - BROWN_MUSHROOM_BLOCK
          - ACACIA_LOG
          - JJUNGLE_LOG
          - PRISMARINE_BRICKS
          - PRISMARINE
          - MUSHROOM_STEM
          - ROSE_BUSH
          - BLUE_ICE
          - SUNFLOWER
          - AZURE_BLUET
          - OXEYE_DAISY
          - LILAC
          - SUGAR_CANE_BLOCK
          - PEONY
          - INFESTED_STONE_BRICKS
          - CORNFLOWER
          - LILY_OF_THE_VALLEY
          - PINK_TULIP
          - RED_TULIP
          - ORANGE_TULIP
          - WHITE_TULIP
          - ALLIUM
          - FARMLAND
          - BROWN_MUSHROOM
          - CACTUS
          - SWEET_BERRY_BUSH
          - POLISHED_GRANITE
          - BLUE_ORCHID
          - PUMPKIN
          - DARK_PRISMARINE
          - SEA_LANTERN
          - TERRACOTTA
          - YELLOW_TERRACOTTA
          - ORANGE_TERRACOTTA
          - MELON
          - WHITE_TERRACOTTA
          - LIGHT_BLUE_TERRACOTTA
          - BLUE_TERRACOTTA

          - NETHERRACK
          - BASALT
          - BLACKSTONE
          - SOUL_SAND
          - SOUL_SOIL
          - MAGMA_BLOCK
          - GRAVEL
          - NETHER_QUARTZ_ORE
          - NETHER_WART_BLOCK
          - NETHER_GOLD_ORE
          - NETHER_BRICK
          - CRIMSON_NYLIUM
          - WARPED_WART_BLOCK
          - WARPED_NYLIUM
          - CRIMSON_STEM
          - POLISHED_BLACKSTONE
          - WARPED_STEM
          - CHISELED_POLISHED_BLACKSTONE
          - GLOWSTONE
          - SHROOMLIGHT
          - ANCIENT_DEBRIS
          - BONE_BLOCK
          - POLISHED_BASALT
          - CHISELED_POLISHED_BLACKSTONE

          - END_STONE
          - PURPUR_BLOCK
          - PURPUR_STAIRS
          - PURPUR_PILLAR
          - END_STONE_BRICKS
          - MAGENTA_STAINED_GLASS_PANE
          - PURPUR_SLAB
          - END_ROD
  # To create a custom configuration in the path of log.yml "CustomConfig".
  # Command: /crp configbuilder custom <Type> <Group>
  Custom:
    OfflinePlayer-UUID:
      Type: OfflinePlayer-UUID
      Format:
        Title: "%title%:"
        Row-Line: true
        Value: "  - %value%"
        #Value: "%value%:"
        #Split: ", "
      # Can be UUID or Player name.
      Ignore-List: []
    OfflinePlayer-Name:
      Type: OfflinePlayer-Name
      Format:
        Title: "%title%:"
        Row-Line: true
        Value: "  - %value%"
        #Split: ", "
      Ignore-List: []
    Example-Entity-Group:
      Type: entity
      Format:
        Title: "%title%:"
        Row-Line: true
        Value: "  - %value%"
        #Split: ", "
      List:
        - Boss
      Ignore-List: []
    Example-Material-Group:
      Type: material
      Format:
        Title: "%title%:"
        Row-Line: true
        Value: "  - %value%"
        #Split: ", "
      List:
        - Chest
      Ignore-List: []

Message:
  prefix: "&7[&dCorePlus&7]&r"
  unknownCommand: "%prefix% &fUnknown command."
  noPermission: "%prefix% &cYou do not have permission to use that command!"
  configReload: "%prefix% &aConfiguration(s) Reloaded!"
  targetNotFound: "%prefix% &cThe player &c%targetplayer% &ccould not be found!"
  cooldown: "%prefix% &fPlease try it again later."
  featureDisabled: "%prefix% &cThis feature is disabled."
  dependNotFound: "%prefix% &cThis feature needs plugin %plugin%."
  groupNotFound: "%prefix% &cCan not find: %group%"
  onlyPlayer: "%prefix% &cThis command can only executing from player."
  noFlagPerm: "%prefix% &cYou dont have &6%flag% &cpermission<s> here."
  notEnoughMoney: "%prefix% &cYou need %pricetype%: %price% - Balance: %balance%"
  notEnoughMoneyTarget: "%prefix% &c%targetplayer% need %pricetype%: %price% - Balance: %balance%"
  inventoryFull: "%prefix% &cYou don't have enough inventory space."
  inventoryFullTarget: '%prefix% &c%targetplayer% dont have enough inventory space.'
  noShopItem: "%prefix% &cYou can not buy this block."
  buySuccess: "%prefix% &aSuccess buy &e%item% x%amount% &afor %price% %pricetype% &8- &a%pricetype%: %balance%"
  buyTargetSuccess: "%prefix% &aSuccess buy &e%item% x%amount% &afor %price% %pricetype% for %targetplayer% &8- &a%pricetype%: %balance%"
  runcmdOther: "%prefix% &eExecuted command for %targetplayer%: %value%"
  runcmdCustomOther: "%prefix% &eExecuted custom command for %targetplayer%: %group%"
  foundAmount: "%prefix% &eFound %amount% %value%."
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩ &d&lCorePlus &8▩▩▩▩▩▩▩▩▩▩"
    help: "&f/coreplus help &8- &7This help menu."
    reload: "&f/coreplus reload &8- &7Reloads config file."
    version: "&f/coreplus version &8- &7Checks the plugin version and updates."
    testPlaceholder: "&f/coreplus test placeholder <placeholder> [player] &8- &7Toggles the placeholder debug mode."
    configbuilderCustom: "&f/coreplus configbuilder custom <group> &8- &7Creates a configuration for custom group."
    configbuilderGroup: "&f/coreplus configbuilder group &8- &7Creates a configuration for group.yml."
    cmdgroup: "&f/coreplus cmdgroup [player] <group> &8- &7Executes custom group command for a player."
    cmd: "&f/coreplus cmd <command> &8- &7Executes custom command."
    cmdplayer: "&f/coreplus cmdplayer <player> <command> &8- &7Executes custom command for a player."
    cmdonline: "&f/coreplus cmdonline <player> <expiration> <command> &8- &7Executes the custom command after the player joined the server."
  Translation:
    console: "Console"
    empty: "empty"
    noTargets: "No Target"
    noData: "No Data"
    money: "money"
    points: "points"
    res_points: "points"
    blocks: "blocks"
    chunks: "chunks"
    resCreate: "create residence"
    resChangeSize: "change residence size"
    fishing: "fishing"
    usingItem: "using items"
    interactBlock: "interact blocks"
    interactEntity: "interact entities"
    damamgeEntity: "damage entities"
    dropItem: "drop items"
    pickupItem: "pickup items"
    colorA: "green"
    colorB: "aqua"
    colorC: "red"
    colorD: "light_purple"
    colorE: "yellow"
    colorF: "white"
    color0: "black"
    color1: "dark_blue"
    color2: "dark_green"
    color3: "dark_aqua"
    color4: "dark_red"
    color5: "dark_purple"
    color6: "gold"
    color7: "gray"
    color8: "dark_gray"
    color9: "blue"