name: CorePlus
main: tw.momocraft.coreplus.CorePlus
author: Momocraft
api-version: 1.13
version: 1.0.0
description: The API contains all utils for my plugins.
softdepend: [Vault, PlayerPoints, GemsEconomy, PlaceHolderAPI, LuckPerms, MysqlPlayerDataBridge, CMI, Residence, ItemJoin, MythicMobs, PvPManager]

commands:
  coreplus:
    description: Displays main command menu.
    permission: coreplus.admin
    aliases: [crp]
    usage: |
      /coreplus

permissions:
  coreplus.*:
    description: Allows use of all commands and features.
    default: op
    children:
<<<<<<< Updated upstream
      coreplus.use: true
      CorePlus.command.*: true
      CorePlus.bypass.*: true
  CorePlus.use:
    description: Allows use of basic commands.
    default: true
  CorePlus.command.*:
    description: Allows use all commands.
    default: op
    children:
      CorePlus.command.reload: true
      CorePlus.command.version: true
      CorePlus.command.test: true
      CorePlus.command.cmd: true
      CorePlus.command.configbuilder: true
  CorePlus.command.reload:
    description: Allows use of /coreplus command reload.
    default: op
  CorePlus.command.version:
    description: Allows use of command /coreplus version.
    default: op
  CorePlus.command.test:
    description: Allows use of command /coreplus test.
    default: op
  CorePlus.command.cmd:
    description: Allows use of command /coreplus cmd/cmdplayer/cmdonline.
    default: op
  CorePlus.command.configbuilder:
    description: Allows use of command /coreplus configbuilder.
=======
      coreplus.admin: true
  CorePlus.admin:
    description: Allows use of all commands and features.
>>>>>>> Stashed changes
    default: op